version: '3.8'

volumes:
    db-data:

services:
    front:
        container_name: front-sample
        build:
            context: ./front
            dockerfile: ./Dockerfile
        ports:
            - 3003:3003
        environment:
            TZ: Asia/Tokyo
        tty: true
        volumes:
            - ./front:/front

    back:
        container_name: back-sample
        build:
            context: ./back
            dockerfile: ./Dockerfile
        command: python /back/manage.py runserver 0.0.0.0:8008
        ports:
            - 8008:8008
        environment:
            TZ: Asia/Tokyo
        tty: true
        volumes:
            - ./back:/back
        depends_on:
            - db

    db:
        container_name: postgres
        image: postgres:14.5-alpine
        ports:
            - 6541:5432
        environment:
            POSTGRES_USER: dev
            POSTGRES_PASSWORD: passwd
            POSTGRES_DB: dev
            POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
            TZ: Asia/Tokyo
        hostname: postgres
        volumes:
            - db-data:/var/lib/postgresql/data